/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DataIngestion.DBIntegrator;
import DataIngestion.IApiIntegrator;
import DataIngestion.MultiDrawIntegrator;
import java.awt.Cursor;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.Objects;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingWorker;
import model.GameDrawResults;
import model.WinningColumn;

/**
 *
 * @author jkanaks
 */
public class DiplayDataByDrawFrame extends javax.swing.JFrame {

    private MenuOverlay menuOverlay = new MenuOverlay();
    private List<GameDrawResults> gameDrawResults;
    //List of API Responce for winning numbers
    private List<WinningColumn> winningColumns;

    /**
     * Creates new form NewJFrame
     */
    public DiplayDataByDrawFrame() {
        initComponents();
        setComboValues();
        progressBar.setVisible(false);
        JLblPayoutTitle.setHorizontalAlignment(JLabel.CENTER);
        JLbChartTitle.setHorizontalAlignment(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tzokerDataPanel = new javax.swing.JPanel();
        JPnlChartByDraw = new javax.swing.JPanel();
        JPnlGoBack = new javax.swing.JPanel();
        JLbGoBackIcon = new javax.swing.JLabel();
        JLbGoBackText = new javax.swing.JLabel();
        JPnlShowData = new javax.swing.JPanel();
        JLblYear = new javax.swing.JLabel();
        JCmbYear = new javax.swing.JComboBox<>();
        JLblMonth = new javax.swing.JLabel();
        JCmbMonth = new javax.swing.JComboBox<>();
        JLblFiller = new javax.swing.JLabel();
        JPnlGetDrawData = new javax.swing.JPanel();
        JLblExecuteIcon = new javax.swing.JLabel();
        JLblExecuteText = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        JLblJackpotsTitle = new javax.swing.JLabel();
        JLblDraws = new javax.swing.JLabel();
        JLblDrawsTitle = new javax.swing.JLabel();
        JLblPayout = new javax.swing.JLabel();
        JLblPayoutTitle = new javax.swing.JLabel();
        JLblJackpots = new javax.swing.JLabel();
        JLbChartTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tzokerDataPanel.setBackground(new java.awt.Color(190, 139, 6));
        tzokerDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tzokerDataPanel.add(JPnlChartByDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 670, 170));

        JPnlGoBack.setBackground(new java.awt.Color(190, 139, 6));
        JPnlGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPnlGoBack.setMinimumSize(new java.awt.Dimension(200, 55));
        JPnlGoBack.setPreferredSize(new java.awt.Dimension(200, 55));
        JPnlGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlGoBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlGoBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlGoBackMouseExited(evt);
            }
        });
        JPnlGoBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbGoBackIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLbGoBackIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/arrow-left1.png"))); // NOI18N
        JPnlGoBack.add(JLbGoBackIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        JLbGoBackText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLbGoBackText.setForeground(new java.awt.Color(255, 255, 255));
        JLbGoBackText.setText("Επιστροφή");
        JPnlGoBack.add(JLbGoBackText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 50));

        tzokerDataPanel.add(JPnlGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        JPnlShowData.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JPnlShowData.setMinimumSize(new java.awt.Dimension(70, 55));
        JPnlShowData.setOpaque(false);
        JPnlShowData.setPreferredSize(new java.awt.Dimension(370, 55));

        JLblYear.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        JLblYear.setForeground(new java.awt.Color(255, 255, 255));
        JLblYear.setLabelFor(JCmbYear);
        JLblYear.setText("Έτος Κλήρωσης:");
        JLblYear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JLblYear.setPreferredSize(new java.awt.Dimension(90, 14));
        JPnlShowData.add(JLblYear);

        JCmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCmbYear.setMaximumSize(new java.awt.Dimension(56, 22));
        JCmbYear.setMinimumSize(new java.awt.Dimension(56, 22));
        JCmbYear.setPreferredSize(new java.awt.Dimension(65, 25));
        JPnlShowData.add(JCmbYear);

        JLblMonth.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        JLblMonth.setForeground(new java.awt.Color(255, 255, 255));
        JLblMonth.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JLblMonth.setText("Μήνας Κλήρωσης:");
        JLblMonth.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JLblMonth.setPreferredSize(new java.awt.Dimension(100, 14));
        JPnlShowData.add(JLblMonth);

        JCmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JCmbMonth.setMaximumSize(new java.awt.Dimension(56, 22));
        JCmbMonth.setMinimumSize(new java.awt.Dimension(56, 22));
        JCmbMonth.setOpaque(false);
        JCmbMonth.setPreferredSize(new java.awt.Dimension(110, 25));
        JPnlShowData.add(JCmbMonth);

        JLblFiller.setPreferredSize(new java.awt.Dimension(50, 14));
        JLblFiller.setRequestFocusEnabled(false);
        JPnlShowData.add(JLblFiller);

        tzokerDataPanel.add(JPnlShowData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 690, 60));

        JPnlGetDrawData.setBackground(new java.awt.Color(190, 139, 6));
        JPnlGetDrawData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPnlGetDrawData.setMinimumSize(new java.awt.Dimension(200, 55));
        JPnlGetDrawData.setPreferredSize(new java.awt.Dimension(200, 55));
        JPnlGetDrawData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlGetDrawDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlGetDrawDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlGetDrawDataMouseExited(evt);
            }
        });
        JPnlGetDrawData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLblExecuteIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLblExecuteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/play3.png"))); // NOI18N
        JPnlGetDrawData.add(JLblExecuteIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        JLblExecuteText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLblExecuteText.setForeground(new java.awt.Color(255, 255, 255));
        JLblExecuteText.setText("Εμφάνιση Αποτελεσμάτων");
        JPnlGetDrawData.add(JLblExecuteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 170, 50));

        tzokerDataPanel.add(JPnlGetDrawData, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 270, -1));

        progressBar.setPreferredSize(new java.awt.Dimension(695, 15));
        tzokerDataPanel.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 470, 700, 20));

        JLblJackpotsTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLblJackpotsTitle.setForeground(new java.awt.Color(255, 255, 255));
        JLblJackpotsTitle.setText("Αριθμός ΤΖΑΚ-ΠΟΤ");
        JLblJackpotsTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tzokerDataPanel.add(JLblJackpotsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 120, 30));

        JLblDraws.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        JLblDraws.setForeground(new java.awt.Color(51, 51, 51));
        JLblDraws.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLblDraws.setText("-");
        JLblDraws.setOpaque(true);
        tzokerDataPanel.add(JLblDraws, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 110));

        JLblDrawsTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLblDrawsTitle.setForeground(new java.awt.Color(255, 255, 255));
        JLblDrawsTitle.setText("Αριθμός Κληρώσεων");
        JLblDrawsTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tzokerDataPanel.add(JLblDrawsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 30));

        JLblPayout.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        JLblPayout.setForeground(new java.awt.Color(51, 51, 51));
        JLblPayout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLblPayout.setText("-");
        JLblPayout.setOpaque(true);
        tzokerDataPanel.add(JLblPayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 380, 110));

        JLblPayoutTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLblPayoutTitle.setForeground(new java.awt.Color(255, 255, 255));
        JLblPayoutTitle.setText("Διανεμόμενα Κέρδη");
        JLblPayoutTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tzokerDataPanel.add(JLblPayoutTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 380, 30));

        JLblJackpots.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        JLblJackpots.setForeground(new java.awt.Color(51, 51, 51));
        JLblJackpots.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLblJackpots.setText("-");
        JLblJackpots.setOpaque(true);
        tzokerDataPanel.add(JLblJackpots, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 120, 110));

        JLbChartTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLbChartTitle.setForeground(new java.awt.Color(255, 255, 255));
        JLbChartTitle.setText("Κέρδη ανα Κλήρωση");
        JLbChartTitle.setFocusCycleRoot(true);
        tzokerDataPanel.add(JLbChartTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 262, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tzokerDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tzokerDataPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPnlGetDrawDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGetDrawDataMouseClicked

        if (!JPnlGetDrawData.isEnabled()) {
            return;
        }       
        execForm();
    }//GEN-LAST:event_JPnlGetDrawDataMouseClicked

    private void JPnlGetDrawDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGetDrawDataMouseEntered
        menuOverlay.setHilighted((JPanel) evt.getSource(), true);
    }//GEN-LAST:event_JPnlGetDrawDataMouseEntered

    private void JPnlGetDrawDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGetDrawDataMouseExited
        menuOverlay.setHilighted((JPanel) evt.getSource(), false);
    }//GEN-LAST:event_JPnlGetDrawDataMouseExited

    private void JPnlGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGoBackMouseClicked
        this.dispose();
    }//GEN-LAST:event_JPnlGoBackMouseClicked

    private void JPnlGoBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGoBackMouseEntered
        menuOverlay.setHilighted((JPanel) evt.getSource(), true);
    }//GEN-LAST:event_JPnlGoBackMouseEntered

    private void JPnlGoBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGoBackMouseExited
        menuOverlay.setHilighted((JPanel) evt.getSource(), false);
    }//GEN-LAST:event_JPnlGoBackMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCmbMonth;
    private javax.swing.JComboBox<String> JCmbYear;
    private javax.swing.JLabel JLbChartTitle;
    private javax.swing.JLabel JLbGoBackIcon;
    private javax.swing.JLabel JLbGoBackText;
    private javax.swing.JLabel JLblDraws;
    private javax.swing.JLabel JLblDrawsTitle;
    private javax.swing.JLabel JLblExecuteIcon;
    private javax.swing.JLabel JLblExecuteText;
    private javax.swing.JLabel JLblFiller;
    private javax.swing.JLabel JLblJackpots;
    private javax.swing.JLabel JLblJackpotsTitle;
    private javax.swing.JLabel JLblMonth;
    private javax.swing.JLabel JLblPayout;
    private javax.swing.JLabel JLblPayoutTitle;
    private javax.swing.JLabel JLblYear;
    private javax.swing.JPanel JPnlChartByDraw;
    private javax.swing.JPanel JPnlGetDrawData;
    private javax.swing.JPanel JPnlGoBack;
    private javax.swing.JPanel JPnlShowData;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPanel tzokerDataPanel;
    // End of variables declaration//GEN-END:variables

    //Populate Year and month Comboboxes
    private void setComboValues() {

        this.JCmbYear.removeAllItems();
        this.JCmbMonth.removeAllItems();

        for (int i = Calendar.getInstance().get(Calendar.YEAR); i >= 2000; i--) {
            this.JCmbYear.addItem(String.valueOf(i));
        }

        this.JCmbMonth.addItem("Ιανουάριος");
        this.JCmbMonth.addItem("Φεβρουάριος");
        this.JCmbMonth.addItem("Μάρτιος");
        this.JCmbMonth.addItem("Απρίλιος");
        this.JCmbMonth.addItem("Μάιος");
        this.JCmbMonth.addItem("Ιούνιος");
        this.JCmbMonth.addItem("Ιούλιος");
        this.JCmbMonth.addItem("Αύγουστος");
        this.JCmbMonth.addItem("Σεπτέμβριος");
        this.JCmbMonth.addItem("Οκτώβριος");
        this.JCmbMonth.addItem("Νοέμβριος");
        this.JCmbMonth.addItem("Δεκέμβριος");
    }

    private void startWaiting(JPanel panel) {
        progressBar.setVisible(true);
        progressBar.setIndeterminate(true);
        progressBar.setValue(100);
        tzokerDataPanel.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        panel.grabFocus();
    }

    private void stopWaiting() {
        tzokerDataPanel.setCursor(null); //turn off the wait cursor
        progressBar.setIndeterminate(false);
        progressBar.setVisible(false);
    }
    
    
    public void setYear(String Year) {
        this.JCmbYear.setSelectedItem(Year);
    }

    public void setMonth(int Month) {
        this.JCmbMonth.setSelectedIndex(Month-1);
    }
    
    
    public void execForm(){
    
        startWaiting((JPanel) JPnlGetDrawData);
        menuOverlay.setEnabled(JPnlGetDrawData, false);
        SwingWorker<Void, Void> mySwingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {

                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                int selectedYear = Integer.parseInt(String.valueOf(JCmbYear.getSelectedItem()));
                int selectedMonth = JCmbMonth.getSelectedIndex();
                //Original Start Date
                String initFromDate = "1900-01-01";
                //Start and End dates used in loop
                String fromDate = "1900-01-01";
                String toDate = "1900-01-01";
                //Initialize calendar objects with the user selections
                Calendar cFrom = Calendar.getInstance();
                Calendar cTo = Calendar.getInstance();
                cFrom.set(selectedYear, selectedMonth, 1);
                int lastDayOfMonth = cFrom.getActualMaximum(Calendar.DATE);
                cFrom.set(selectedYear, selectedMonth, 1);
                cTo.set(selectedYear, selectedMonth, 15);
                //Keep the original starting date
                initFromDate = dateFormat.format(cFrom.getTime());

                try {
                    //Split to two calls in order to fetch all data!!
                    //Bug with the API (omits results while reurns stats code 200!!! when the date range is close to 30 days)
                    for (int i = 0; i < 2; i++) {

                        fromDate = dateFormat.format(cFrom.getTime());
                        toDate = dateFormat.format(cTo.getTime());

                        System.out.println("From Date " + fromDate);
                        System.out.println("To Date" + toDate);

                        IApiIntegrator multiDrawIntegrator = new MultiDrawIntegrator();
                        multiDrawIntegrator.addAPIargument("gameID", "5104");
                        multiDrawIntegrator.addAPIargument("fromDate", fromDate);
                        multiDrawIntegrator.addAPIargument("toDate", toDate);
                        //Fetch data
                        multiDrawIntegrator.loadDataFromAPI();
                        List<GameDrawResults> gameDrawResults_Current = (List<GameDrawResults>) multiDrawIntegrator.getDataObject(GameDrawResults.class);
                        List<WinningColumn> winningColumns_Current = (List<WinningColumn>) multiDrawIntegrator.getDataObject(WinningColumn.class);

                        if (Objects.isNull(gameDrawResults)) {
                            gameDrawResults = (List<GameDrawResults>) multiDrawIntegrator.getDataObject(GameDrawResults.class);
                        } else {
                            //Append at the top to maintain table sorting on draw_id, Win Category
                            gameDrawResults.addAll(0, gameDrawResults_Current);
                        }
                        if (Objects.isNull(winningColumns)) {
                            winningColumns = (List<WinningColumn>) multiDrawIntegrator.getDataObject(WinningColumn.class);
                        } else {
                            //Append at the top to maintain sorting on draw_id
                            winningColumns.addAll(0, winningColumns_Current);
                        }
                        cFrom.set(selectedYear, selectedMonth, 16);
                        cTo.set(selectedYear, selectedMonth, lastDayOfMonth);
                    }
                    //Write to DB ONLY missing draw data
                    DBIntegrator.setDrawResults(winningColumns, gameDrawResults, DBIntegrator.Operation.FORCE_INSERT);
                    //fetch aggregated data
                    DBIntegrator.AggregatedDrawData aggregatedDrawData = DBIntegrator.getDataForMonth(5104, initFromDate, toDate);
                    JLblDraws.setText(String.valueOf(aggregatedDrawData.getNumberOfDraws()));
                    JLblPayout.setText(String.format("%,.2f", aggregatedDrawData.getPayoutAmount()));
                    JLblJackpots.setText(String.valueOf(aggregatedDrawData.getNumberOfJackpots()));
                    //Show bar Chart for draws
                    JPnlChartByDraw.removeAll();
                    DrawsBarChart drawsBarChart = new DrawsBarChart(5104, initFromDate, toDate, String.valueOf(JCmbMonth.getSelectedItem()));
                    drawsBarChart.setPreferredSize(new Dimension(700, 170));
                    JPnlChartByDraw.add(drawsBarChart);
                    JPnlChartByDraw.repaint();
                    JPnlChartByDraw.revalidate();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Παρουσιάστηκε σφάλμα κατα την παρουσίαση των δεδομένων." + e.getMessage(),
                             "Παρουσίαση Δεδομένων", JOptionPane.ERROR_MESSAGE);
                    System.out.println(e);
                } finally {
                    //Restore initial UI status
                    stopWaiting();
                    menuOverlay.setEnabled((JPanel) JPnlGetDrawData, true);
                }
                return null;
            }
        };
        mySwingWorker.execute();
    
    }
    
}
