/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class MainFrame extends javax.swing.JFrame {
    //Application Name
    private final String APP_NAME = "JokerGame-Stats";
    //Store Current mouse cursor position
    private int xAxisMousePos;
    private int yAxisMousePos;
 //   private JPanel selectePanelLevel01;
    private MenuOverlay menuOverlay = new MenuOverlay();
    
    
    /**
     * Creates new form MainMenu
     */
    public MainFrame() {
        initComponents();                
        //Check DB connection during startup
        String connectionString = "jdbc:derby://localhost/L10L;user=TzokerStats;password=pass";
        Connection connection = null;
        
        try {
            connection = DriverManager.getConnection(connectionString);            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Παρουσιάστηκε σφάλμα κατα την σύνδεση στην βάση δεδομένων.\n" + ex,
                                "Πρόβλημα κατα την σύνδεση στον derby Server", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JPnlMain = new javax.swing.JPanel();
        JPnlHeader = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        JPnlMainMenu = new javax.swing.JPanel();
        JPnlGetDataMenu = new javax.swing.JPanel();
        JLblGetDataTitle = new javax.swing.JLabel();
        JLblGetDataIcon = new javax.swing.JLabel();
        JPnlMenuReport = new javax.swing.JPanel();
        JLbDisplayDataText = new javax.swing.JLabel();
        JLbDisplayDataIcon = new javax.swing.JLabel();
        JPnlMenuStats = new javax.swing.JPanel();
        JLbDisplayStatsText = new javax.swing.JLabel();
        JLbDisplayStatsIcon = new javax.swing.JLabel();
        JPnlMenuExit = new javax.swing.JPanel();
        JLbExitText = new javax.swing.JLabel();
        JLbExitIcon = new javax.swing.JLabel();
        JPnlWorkingPanel = new javax.swing.JPanel();
        JLbFootnote = new javax.swing.JLabel();
        JLbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JPnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        JPnlHeader.setOpaque(false);
        JPnlHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JPnlHeaderMouseDragged(evt);
            }
        });
        JPnlHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlHeaderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPnlHeaderMousePressed(evt);
            }
        });
        JPnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close.png"))); // NOI18N
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        JPnlHeader.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 0, 40, 50));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minus_1.png"))); // NOI18N
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        JPnlHeader.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 40, 50));

        JPnlMain.add(JPnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 50));

        JPnlMainMenu.setBackground(new java.awt.Color(190, 139, 6));

        JPnlGetDataMenu.setBackground(new java.awt.Color(190, 139, 6));
        JPnlGetDataMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPnlGetDataMenu.setMinimumSize(new java.awt.Dimension(250, 50));
        JPnlGetDataMenu.setPreferredSize(new java.awt.Dimension(250, 55));
        JPnlGetDataMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlGetDataMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlGetDataMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlGetDataMenuMouseExited(evt);
            }
        });
        JPnlGetDataMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLblGetDataTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLblGetDataTitle.setForeground(new java.awt.Color(255, 255, 255));
        JLblGetDataTitle.setText("Διαχείριση Δεδομένων Τζόκερ");
        JPnlGetDataMenu.add(JLblGetDataTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 50));

        JLblGetDataIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLblGetDataIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database.png"))); // NOI18N
        JPnlGetDataMenu.add(JLblGetDataIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        JPnlMainMenu.add(JPnlGetDataMenu);

        JPnlMenuReport.setBackground(new java.awt.Color(190, 139, 6));
        JPnlMenuReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPnlMenuReport.setPreferredSize(new java.awt.Dimension(250, 53));
        JPnlMenuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlMenuReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlMenuReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlMenuReportMouseExited(evt);
            }
        });
        JPnlMenuReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbDisplayDataText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLbDisplayDataText.setForeground(new java.awt.Color(255, 255, 255));
        JLbDisplayDataText.setText("Προβολή Δεδομένων Τζόκερ");
        JPnlMenuReport.add(JLbDisplayDataText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 50));

        JLbDisplayDataIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLbDisplayDataIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/file-text.png"))); // NOI18N
        JPnlMenuReport.add(JLbDisplayDataIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        JPnlMainMenu.add(JPnlMenuReport);

        JPnlMenuStats.setBackground(new java.awt.Color(190, 139, 6));
        JPnlMenuStats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPnlMenuStats.setPreferredSize(new java.awt.Dimension(250, 53));
        JPnlMenuStats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlMenuStatsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlMenuStatsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlMenuStatsMouseExited(evt);
            }
        });
        JPnlMenuStats.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbDisplayStatsText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLbDisplayStatsText.setForeground(new java.awt.Color(255, 255, 255));
        JLbDisplayStatsText.setText("Προβολή Στατιστικών Τζόκερ");
        JPnlMenuStats.add(JLbDisplayStatsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 50));

        JLbDisplayStatsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLbDisplayStatsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stats-dots.png"))); // NOI18N
        JPnlMenuStats.add(JLbDisplayStatsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        JPnlMainMenu.add(JPnlMenuStats);

        JPnlMenuExit.setBackground(new java.awt.Color(190, 139, 6));
        JPnlMenuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPnlMenuExit.setPreferredSize(new java.awt.Dimension(250, 53));
        JPnlMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlMenuExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlMenuExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlMenuExitMouseExited(evt);
            }
        });
        JPnlMenuExit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLbExitText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLbExitText.setForeground(new java.awt.Color(255, 255, 255));
        JLbExitText.setText("Έξοδος");
        JPnlMenuExit.add(JLbExitText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 50));

        JLbExitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLbExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        JPnlMenuExit.add(JLbExitIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 50));

        JPnlMainMenu.add(JPnlMenuExit);

        JPnlMain.add(JPnlMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 222, 244, 300));

        JPnlWorkingPanel.setOpaque(false);

        javax.swing.GroupLayout JPnlWorkingPanelLayout = new javax.swing.GroupLayout(JPnlWorkingPanel);
        JPnlWorkingPanel.setLayout(JPnlWorkingPanelLayout);
        JPnlWorkingPanelLayout.setHorizontalGroup(
            JPnlWorkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        JPnlWorkingPanelLayout.setVerticalGroup(
            JPnlWorkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        JPnlMain.add(JPnlWorkingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 860, 520));

        JLbFootnote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLbFootnote.setForeground(new java.awt.Color(204, 204, 204));
        JLbFootnote.setText(" ΗΛΕ-46/Ομάδα 1   Λιανάκης Ιωάννης | Οικονόμου Παναγιώτης | Κανάκης Ιωάννης");
        JPnlMain.add(JLbFootnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 950, 40));

        JLbBackground.setBackground(new java.awt.Color(255, 195, 20));
        JLbBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MainForm_4.png"))); // NOI18N
        JPnlMain.add(JLbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setTitle(APP_NAME);
        getAccessibleContext().setAccessibleName(APP_NAME);        
    }//GEN-LAST:event_formWindowOpened

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        setState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void JPnlHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JPnlHeaderMouseClicked

    private void JPnlHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlHeaderMousePressed
        xAxisMousePos = evt.getX();
        yAxisMousePos = evt.getY();
    }//GEN-LAST:event_JPnlHeaderMousePressed

    private void JPnlHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlHeaderMouseDragged
        int xPosOnScreen = evt.getXOnScreen();
        int yPosOnScreen = evt.getYOnScreen();
        this.setLocation(xPosOnScreen - xAxisMousePos, yPosOnScreen - yAxisMousePos);
    }//GEN-LAST:event_JPnlHeaderMouseDragged

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        closeApp();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void JPnlGetDataMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGetDataMenuMouseEntered
        menuOverlay.setHilighted((JPanel)evt.getSource(), true);
    }//GEN-LAST:event_JPnlGetDataMenuMouseEntered

    private void JPnlGetDataMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGetDataMenuMouseExited
        menuOverlay.setHilighted((JPanel)evt.getSource(), false);
    }//GEN-LAST:event_JPnlGetDataMenuMouseExited

    private void JPnlMenuExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuExitMouseEntered
        menuOverlay.setHilighted((JPanel)evt.getSource(), true);
    }//GEN-LAST:event_JPnlMenuExitMouseEntered

    private void JPnlMenuExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuExitMouseExited
        menuOverlay.setHilighted((JPanel)evt.getSource(), false);
    }//GEN-LAST:event_JPnlMenuExitMouseExited

    private void JPnlMenuStatsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuStatsMouseEntered
        menuOverlay.setHilighted((JPanel)evt.getSource(), true);
    }//GEN-LAST:event_JPnlMenuStatsMouseEntered

    private void JPnlMenuStatsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuStatsMouseExited
        menuOverlay.setHilighted((JPanel)evt.getSource(), false);
    }//GEN-LAST:event_JPnlMenuStatsMouseExited

    private void JPnlMenuReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuReportMouseEntered
        menuOverlay.setHilighted((JPanel)evt.getSource(), true);
    }//GEN-LAST:event_JPnlMenuReportMouseEntered

    private void JPnlMenuReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuReportMouseExited
        menuOverlay.setHilighted((JPanel)evt.getSource(), false);
    }//GEN-LAST:event_JPnlMenuReportMouseExited

    private void JPnlGetDataMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlGetDataMenuMouseClicked
        //Prepare DataFrame and present it modally
        showFrame((JPanel)evt.getSource(), new GetDataFrame());        
    }//GEN-LAST:event_JPnlGetDataMenuMouseClicked

    private void JPnlMenuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuReportMouseClicked
        //Present Joker Data
        showFrame((JPanel)evt.getSource(), new DiplayDataByMonthFrame());           
    }//GEN-LAST:event_JPnlMenuReportMouseClicked

    private void JPnlMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuExitMouseClicked
        closeApp();
    }//GEN-LAST:event_JPnlMenuExitMouseClicked

    private void JPnlMenuStatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlMenuStatsMouseClicked
        //Present Joker Table and Chart Stats
        showFrame((JPanel)evt.getSource(), new StatsMainFrame());
    }//GEN-LAST:event_JPnlMenuStatsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbBackground;
    private javax.swing.JLabel JLbDisplayDataIcon;
    private javax.swing.JLabel JLbDisplayDataText;
    private javax.swing.JLabel JLbDisplayStatsIcon;
    private javax.swing.JLabel JLbDisplayStatsText;
    private javax.swing.JLabel JLbExitIcon;
    private javax.swing.JLabel JLbExitText;
    private javax.swing.JLabel JLbFootnote;
    private javax.swing.JLabel JLblGetDataIcon;
    private javax.swing.JLabel JLblGetDataTitle;
    private javax.swing.JPanel JPnlGetDataMenu;
    private javax.swing.JPanel JPnlHeader;
    private javax.swing.JPanel JPnlMain;
    private javax.swing.JPanel JPnlMainMenu;
    private javax.swing.JPanel JPnlMenuExit;
    private javax.swing.JPanel JPnlMenuReport;
    private javax.swing.JPanel JPnlMenuStats;
    private javax.swing.JPanel JPnlWorkingPanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMinimize;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables


    private void showFrame(JPanel selectedPanel, javax.swing.JFrame frame) {                                        
        //Present Joker Data
        if (Objects.isNull(menuOverlay.getSelected()) || 
                !menuOverlay.getSelected().equals(selectedPanel)){                    
            //Add the selected panel in the main window            
            JPnlWorkingPanel.removeAll();
            JPnlWorkingPanel.repaint();
            JPnlWorkingPanel.revalidate();

            JPnlWorkingPanel.add(frame.getContentPane());        
            JPnlWorkingPanel.repaint();
            JPnlWorkingPanel.revalidate();
            //Make current item menu active
            menuOverlay.setSelected(selectedPanel);   
            
            //deseleect other
            //menuOverlay.setSelected(menuData);
            menuOverlay.deselectAll(JPnlMainMenu);
        }        
    }     
    
    /*
        Gracefully close app
    */
    private void closeApp(){            
        Object[] options = {"Όχι", "Ναι"};
        int userSelection = JOptionPane.showOptionDialog(null,
                "Θέλετε σίγουρα να κλείσετε την εφαρμογή;",
                APP_NAME,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);

        if (userSelection == 1) {
            try {
                //Stop DerbyDB engine
                Process process = Runtime.getRuntime().exec("cmd /c start /b stopNetworkServer.bat", null, new File("db"));
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }finally {            
                System.exit(0);
            }                        
        }        
    }
}
