/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JPanel;
import DataIngestion.WinningColumnStats;
import javax.swing.table.DefaultTableModel;

import java.io.FileOutputStream;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Panes
 */
public class StatsTableFrame extends javax.swing.JFrame {

    //Object to manipulate the menu behaviour
    private MenuOverlay menuOverlay = new MenuOverlay();
    public WinningColumnStats totaNumberStats;

    /**
     * Creates new form TableDataFrame
     */
    public StatsTableFrame() {
        initComponents();

        //Init Dialog box to save pdf
        dirPicker = new JFileChooser() {
            @Override
            public void approveSelection() {
                File f = getSelectedFile();
                if (f.exists() && getDialogType() == SAVE_DIALOG) {
                    int result = JOptionPane.showConfirmDialog(this, "Το αρχείο υπάρχει ήδη. Θέλετε να γίνει αντικατάσταση;", "Υπάρχον αρχείο", JOptionPane.YES_NO_CANCEL_OPTION);
                    switch (result) {
                        case JOptionPane.YES_OPTION:
                            super.approveSelection();
                            return;
                        case JOptionPane.NO_OPTION:
                            return;
                        case JOptionPane.CLOSED_OPTION:
                            return;
                        case JOptionPane.CANCEL_OPTION:
                            cancelSelection();
                            return;
                    }
                }
                super.approveSelection();
            }
        };

        dirPicker.setDialogTitle("Επιλέξτε φάκελο και όνομα PDF αρχείου.");
        //Dialog box Applicable file types
        dirPicker.setAcceptAllFileFilterUsed(false);
        dirPicker.setFileFilter(new FileFilter() {
            public String getDescription() {
                return "PDF Documents (*.pdf)";
            }

            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    String filename = f.getName().toLowerCase();
                    return filename.endsWith(".pdf");
                }
            }
        });
        //Prepare "Open after Save" option
        JCheckBox ChkOpen = new JCheckBox("Άνοιγμα του αρχείου");
        JPanel accessory = new JPanel();
        accessory.setLayout(new FlowLayout());
        accessory.add(ChkOpen);
        dirPicker.setAccessory(accessory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.9
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnlMain = new javax.swing.JPanel();
        JPnlPrintPdf = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JLblPrintPdfIcon = new javax.swing.JLabel();
        JLblPrintPdfText = new javax.swing.JLabel();
        JPnlNumbersA = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        numbersTable = new javax.swing.JTable();
        JLblNumbersATitle = new javax.swing.JLabel();
        JPnlNumbersB = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bonusNumbersTable = new javax.swing.JTable();
        JLblNumbersBTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(190, 139, 6));

        JPnlMain.setBackground(new java.awt.Color(190, 139, 6));

        JPnlPrintPdf.setBackground(new java.awt.Color(190, 139, 6));
        JPnlPrintPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPnlPrintPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPnlPrintPdfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPnlPrintPdfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPnlPrintPdfMouseExited(evt);
            }
        });

        JLblPrintPdfIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-pdf-30.png"))); // NOI18N

        JLblPrintPdfText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLblPrintPdfText.setForeground(new java.awt.Color(255, 255, 255));
        JLblPrintPdfText.setText("Εκτύπωση σε PDF");

        javax.swing.GroupLayout JPnlPrintPdfLayout = new javax.swing.GroupLayout(JPnlPrintPdf);
        JPnlPrintPdf.setLayout(JPnlPrintPdfLayout);
        JPnlPrintPdfLayout.setHorizontalGroup(
            JPnlPrintPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlPrintPdfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLblPrintPdfIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLblPrintPdfText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        JPnlPrintPdfLayout.setVerticalGroup(
            JPnlPrintPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlPrintPdfLayout.createSequentialGroup()
                .addGroup(JPnlPrintPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPnlPrintPdfLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(JPnlPrintPdfLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPnlPrintPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLblPrintPdfText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLblPrintPdfIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPnlNumbersA.setBackground(new java.awt.Color(190, 139, 6));
        JPnlNumbersA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        numbersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Νούμερο", "Εμφανίσεις", "Καθυστερήσεις"
            }
        ));
        jScrollPane2.setViewportView(numbersTable);

        JLblNumbersATitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLblNumbersATitle.setForeground(new java.awt.Color(255, 255, 255));
        JLblNumbersATitle.setText("Αριθμοί Πεντάδας");

        javax.swing.GroupLayout JPnlNumbersALayout = new javax.swing.GroupLayout(JPnlNumbersA);
        JPnlNumbersA.setLayout(JPnlNumbersALayout);
        JPnlNumbersALayout.setHorizontalGroup(
            JPnlNumbersALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNumbersALayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(JLblNumbersATitle)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        JPnlNumbersALayout.setVerticalGroup(
            JPnlNumbersALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNumbersALayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLblNumbersATitle)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPnlNumbersB.setBackground(new java.awt.Color(190, 139, 6));
        JPnlNumbersB.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bonusNumbersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Νούμερο", "Εμφανίσεις", "Καθυστερήσεις"
            }
        ));
        jScrollPane1.setViewportView(bonusNumbersTable);

        JLblNumbersBTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLblNumbersBTitle.setForeground(new java.awt.Color(255, 255, 255));
        JLblNumbersBTitle.setText("Αριθμός Τζόκερ");

        javax.swing.GroupLayout JPnlNumbersBLayout = new javax.swing.GroupLayout(JPnlNumbersB);
        JPnlNumbersB.setLayout(JPnlNumbersBLayout);
        JPnlNumbersBLayout.setHorizontalGroup(
            JPnlNumbersBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlNumbersBLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(JLblNumbersBTitle)
                .addContainerGap(137, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        JPnlNumbersBLayout.setVerticalGroup(
            JPnlNumbersBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnlNumbersBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLblNumbersBTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout JPnlMainLayout = new javax.swing.GroupLayout(JPnlMain);
        JPnlMain.setLayout(JPnlMainLayout);
        JPnlMainLayout.setHorizontalGroup(
            JPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlMainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JPnlPrintPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPnlMainLayout.createSequentialGroup()
                        .addComponent(JPnlNumbersA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JPnlNumbersB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        JPnlMainLayout.setVerticalGroup(
            JPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnlMainLayout.createSequentialGroup()
                .addGroup(JPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPnlNumbersA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPnlNumbersB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPnlPrintPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPnlPrintPdfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPrintPdfMouseExited
        menuOverlay.setHilighted((JPanel) evt.getSource(), false);
    }//GEN-LAST:event_JPnlPrintPdfMouseExited

    private void JPnlPrintPdfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPrintPdfMouseEntered
        menuOverlay.setHilighted((JPanel) evt.getSource(), true);
    }//GEN-LAST:event_JPnlPrintPdfMouseEntered

    private void JPnlPrintPdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPnlPrintPdfMouseClicked

        //get open file after save user selection
        JCheckBox openAfterSave = new JCheckBox();
        if (dirPicker.getAccessory() != null) {
            Component[] components = dirPicker.getAccessory().getComponents();
            openAfterSave = (JCheckBox) components[0];
        }
        //Show the dialog and get user response
        int result = dirPicker.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                String selectedFile = dirPicker.getSelectedFile().toString();
                generatePdf(selectedFile);
                if (openAfterSave.isSelected()) {
                    File myFile = new File(selectedFile + ".pdf");
                    Desktop.getDesktop().open(myFile);
                }
            } catch (IOException ex) {
                Logger.getLogger(StatsTableFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Cancel was selected");
        }
    }//GEN-LAST:event_JPnlPrintPdfMouseClicked
    // Populates frame tables with statistics data of winning column
    public void fillTables(WinningColumnStats totalNumberStats) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        numbersTable.setDefaultRenderer(Object.class, centerRenderer);
        bonusNumbersTable.setDefaultRenderer(Object.class, centerRenderer);

        DefaultTableModel numbersModel = (DefaultTableModel) numbersTable.getModel();
        DefaultTableModel bonusNumbersModel = (DefaultTableModel) bonusNumbersTable.getModel();
        Object[] numbersData = new Object[3];
        Object[] bonusNumbersData = new Object[3];

        for (WinningColumnStats.Number number : totalNumberStats.numbers) {
            numbersData[0] = number.number;
            numbersData[1] = number.occurrences;
            numbersData[2] = number.delays;
            numbersModel.addRow(numbersData);
        }
        for (WinningColumnStats.BonusNumber bonusNumber : totalNumberStats.bonusNumbers) {
            bonusNumbersData[0] = bonusNumber.number;
            bonusNumbersData[1] = bonusNumber.occurrences;
            bonusNumbersData[2] = bonusNumber.delays;
            bonusNumbersModel.addRow(bonusNumbersData);
        }

    }
    /* Generates .pdf file in the directory specified  
    Pdf consists of statistics data in table form */
    private void generatePdf(String fileName) throws IOException {
        Document pdf = new Document();
        try {
            PdfWriter writer = PdfWriter.getInstance(pdf, 
                    new FileOutputStream(fileName + ".pdf"));
            pdf.open();

            Font normFont = new Font(Font.FontFamily.HELVETICA, 11, Font.NORMAL);
            String currentDirectory = System.getProperty("user.dir");
            BaseFont baseFont = BaseFont.createFont(currentDirectory + 
                    "\\src\\assets\\Ubuntu-Regular.ttf", 
                    BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
            Font greek = new Font(baseFont, 11);
            Font greek26 = new Font(baseFont, 26);
            Font greek16 = new Font(baseFont, 16);
            greek.setColor(BaseColor.WHITE);
            greek16.setColor(BaseColor.WHITE);
            greek26.setColor(new BaseColor(255, 195, 20));

            PdfContentByte canvas = writer.getDirectContent();

            Rectangle line = new Rectangle(0, 766, 600, 768);
            line.setBackgroundColor(new BaseColor(0, 53, 128));
            canvas.rectangle(line);

            Rectangle rect = new Rectangle(0, 770, 600, 850);
            rect.setBackgroundColor(new BaseColor(0, 53, 128));
            canvas.rectangle(rect);
            ColumnText ct = new ColumnText(writer.getDirectContent());
            ct.setSimpleColumn(rect);

            Paragraph title = new Paragraph();
            title.add(new Paragraph("                                        "
                    + "ΤΖΟΚΕΡ", greek26));
            title.add(new Paragraph("                           "
                    + "Στατιστικά παιχνιδιού: Εμφανίσεις-Καθυστερήσεις", greek16));
            ct.addElement(title);
            ct.go();

            greek.setColor(BaseColor.BLACK);

            ColumnText ctDesc = new ColumnText(writer.getDirectContent());
            ctDesc.setSimpleColumn(335, 250, 580, 345);
            ctDesc.addText(new Phrase("*Οι πίνακες απεικονίζουν πόσο συχνά έχουν "
                    + "εμφανιστεί ή καθυστερήσει να εμφανιστούν οι "
                    + "αριθμοί της νικιτριας στηλης του Τζόκερ από την αρχή του "
                    + "παιχνιδιού μέχρι και σήμερα.", greek));
            ctDesc.go();

            greek.setColor(BaseColor.WHITE);

            // Table with stats of the five numbers of the winning column
            PdfPTable numtable = new PdfPTable(3); 

            PdfPCell c1 = new PdfPCell();
            c1.setBackgroundColor(new BaseColor(0, 53, 128));
            c1.setPadding(5);
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);

            // table headers
            c1.setPhrase(new Phrase("Αριθμοί πεντάδας", greek));
            numtable.addCell(c1);

            c1.setPhrase(new Phrase("Εμφανίσεις", greek));
            numtable.addCell(c1);

            c1.setPhrase(new Phrase("Καθυστερήση", greek));
            numtable.addCell(c1);
            
            // Populate five winning numbers table 
            for (WinningColumnStats.Number number : totaNumberStats.numbers) {
                PdfPCell cell1 = new PdfPCell();
                cell1.setFixedHeight(10);
                cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell1.setPhrase(new Phrase(String.valueOf(number.number), normFont));
                numtable.addCell(cell1);

                PdfPCell cell2 = new PdfPCell();
                cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell2.setPhrase(new Phrase(String.valueOf(number.occurrences), normFont));
                numtable.addCell(cell2);

                PdfPCell cell3 = new PdfPCell();
                cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell3.setPhrase(new Phrase(String.valueOf(number.delays), normFont));
                numtable.addCell(cell3);

            }
            
            // Table with winning column stats of joker number 
            PdfPTable bnumtable = new PdfPTable(3);

            PdfPCell c2 = new PdfPCell();
            c2.setBackgroundColor(new BaseColor(0, 53, 128));
            c2.setPadding(5);
            c2.setHorizontalAlignment(Element.ALIGN_CENTER);

            // table headers
            c1.setPhrase(new Phrase("Αριθμός Τζόκερ", greek));
            bnumtable.addCell(c1);

            c1.setPhrase(new Phrase("Εμφανίσεις", greek));
            bnumtable.addCell(c1);

            c1.setPhrase(new Phrase("Καθυστέρηση", greek));
            bnumtable.addCell(c1);
            
            // Populate joker numbers table 
            for (WinningColumnStats.BonusNumber bonusNumber : 
                    totaNumberStats.bonusNumbers) {
                PdfPCell cell1 = new PdfPCell();
                cell1.setFixedHeight(10);
                cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell1.setPhrase(new Phrase(String.valueOf(
                        bonusNumber.number), normFont));
                bnumtable.addCell(cell1);

                PdfPCell cell2 = new PdfPCell();
                cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell2.setPhrase(new Phrase(
                        String.valueOf(bonusNumber.occurrences), normFont));
                bnumtable.addCell(cell2);

                PdfPCell cell3 = new PdfPCell();
                cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell3.setPhrase(new Phrase(
                        String.valueOf(bonusNumber.delays), normFont));
                bnumtable.addCell(cell3);

            }

            ColumnText ct1 = new ColumnText(writer.getDirectContent());
            ct1.setSimpleColumn(0, 0, 300, 740);
            ct1.addElement(numtable);
            ct1.go();

            ColumnText ct2 = new ColumnText(writer.getDirectContent());
            ct2.setSimpleColumn(301, 0, 600, 740);
            ct2.addElement(bnumtable);
            ct2.go();

            pdf.close();

            JOptionPane.showMessageDialog(null, "Το pdf αρχείο δημιουργήθηκε "
                    + "επιτυχώς στο φάκελο:\n" + fileName,
                    "", JOptionPane.INFORMATION_MESSAGE);

        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(StatsTableFrame.class.getName()).log(
                    Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblNumbersATitle;
    private javax.swing.JLabel JLblNumbersBTitle;
    private javax.swing.JLabel JLblPrintPdfIcon;
    private javax.swing.JLabel JLblPrintPdfText;
    private javax.swing.JPanel JPnlMain;
    private javax.swing.JPanel JPnlNumbersA;
    private javax.swing.JPanel JPnlNumbersB;
    private javax.swing.JPanel JPnlPrintPdf;
    private javax.swing.JTable bonusNumbersTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable numbersTable;
    // End of variables declaration//GEN-END:variables

    private JFileChooser dirPicker;

}
